export interface Course {
  id: number;
  title: string;
  instructor: string;
  totalLessons: number;
  image: string;
  nextLesson: string;
  isPremium: boolean;
  price?: number;
  playlist?: { title: string; url: string; completed: boolean }[];
}

export const allCourses: Course[] = [
  {
    id: 1,
    title: "React Fundamentals",
    instructor: "John Doe",
    totalLessons: 3,
    image: "",
    nextLesson: "Components & Props",
    isPremium: false,
    playlist: [
      { title: "Intro to React", url: "https://youtu.be/s2skans2dP4?si=Y6i2fioLuJQNgJuC", completed: false },
      { title: "JSX Basics", url: "https://youtu.be/9GtB5G2xGTY?si=zD7u_COFiP8bX_TC", completed: false },
      { title: "Props & State", url: "https://youtu.be/uvEAvxWvwOs?si=ZxGAB1kWDnCMV29-", completed: false },
    ],
  },
  {
    id: 2,
    title: "Data Science with Python",
    instructor: "Jane Smith",
    totalLessons: 3,
    image: "",
    nextLesson: "Python Basics",
    isPremium: true,
    price: 24.99,
    playlist: [
      { title: "Python Introduction", url: "https://youtu.be/xkZMUX_oQX4?si=KLaqgArmdQZOLpxX", completed: false },
      { title: "Data Types & Variables", url: "https://youtu.be/LKFrQXaoSMQ?si=zJqfTzEqjBVB0Iyx", completed: false },
      { title: "Control Flow", url: "https://youtu.be/Zp5MuPOtsSY?si=5zYSafJcDq6GJJHJ", completed: false },
    ],
  },
  {
    id: 3,
    title: "AI & Machine Learning",
    instructor: "Alice Brown",
    totalLessons: 3,
    image: "",
    nextLesson: "Intro to ML",
    isPremium: true,
    price: 34.99,
    playlist: [
      { title: "What is AI?", url: "https://youtu.be/ad79nYk2keg?si=qzhWcnfa2OarFdIs", completed: false },
      { title: "Supervised vs Unsupervised Learning", url: "https://youtu.be/W01tIRP_Rqs?si=U0xWlXr3PumhusZ8", completed: false },
      { title: "Machine Learning Algorithms", url: "https://youtu.be/E0Hmnixke2g?si=ZJPawT55LPfwOpfE", completed: false },
    ],
  },
  {
    id: 4,
    title: "Cloud Computing Fundamentals",
    instructor: "Bob Martin",
    totalLessons: 3,
    image: "",
    nextLesson: "Cloud Basics",
    isPremium: true,
    price: 19.99,
    playlist: [
      { title: "Cloud Intro", url: "https://youtu.be/N0SYCyS2xZA?si=bCqTiKw0V1PzHfCv", completed: false },
      { title: "IaaS, PaaS, SaaS Explained", url: "https://youtu.be/36zducUX16w?si=cPrJ9SmuEcZgwMfo", completed: false },
      { title: "Cloud Services Overview", url: "https://youtu.be/36zducUX16w?si=cPrJ9SmuEcZgwMfo", completed: false },
    ],
  },
  {
    id: 5,
    title: "UI/UX Design",
    instructor: "Carol White",
    totalLessons: 3,
    image: "",
    nextLesson: "Design Principles",
    isPremium: false,
    playlist: [
      { title: "What is UX?", url: "https://youtu.be/ODpB9-MCa5s?si=x-D7NYxvA_2apVIz", completed: false },
      { title: "UI Principles", url: "https://youtu.be/NTmh8l-Xl4c?si=P1QTpkmA05KhOHDW", completed: false },
      { title: "Wireframing Basics", url: "https://youtu.be/iyrEStiTZh0?si=92ynYB-RkDN1ksbE", completed: false },
    ],
  },
  {
    id: 6,
    title: "Cybersecurity Basics",
    instructor: "Dave Black",
    totalLessons: 3,
    image: "",
    nextLesson: "Security Fundamentals",
    isPremium: true,
    price: 29.99,
    playlist: [
      { title: "Cybersecurity Intro", url: "https://youtu.be/inWWhr5tnEA?si=qUBDzxYk1bEuJSFN", completed: false },
      { title: "Common Threats", url: "https://youtu.be/Dk-ZqQ-bfy4?si=QQHWUTzqKeJLI_10", completed: false },
      { title: "Basic Security Measures", url: "https://youtu.be/23yJXAzKFS4?si=KN0afNMJYHvUhoXQ", completed: false },
    ],
  },
  {
    id: 7,
    title: "Mobile App Development",
    instructor: "Eve Green",
    totalLessons: 3,
    image: "",
    nextLesson: "Intro to Apps",
    isPremium: false,
    playlist: [
      { title: "Mobile App Intro", url: "https://youtu.be/vDMyIZ2nsS0?si=YzD5g15QK25yggLz", completed: false },
      { title: "React Native Basics", url: "https://youtu.be/gvkqT_Uoahw?si=wcjf0ZIkIVYqjgxd", completed: false },
      { title: "App Deployment", url: "https://youtu.be/RIX4ufelA58?si=5CeidD63Kt2i5gdG", completed: false },
    ],
  },
  {
    id: 8,
    title: "Blockchain Essentials",
    instructor: "Frank Gray",
    totalLessons: 3,
    image: "",
    nextLesson: "Blockchain Basics",
    isPremium: true,
    price: 24.99,
    playlist: [
      { title: "Blockchain Intro", url: "https://youtu.be/yubzJw0uiE4?si=JGfv9XabCb2rd2QH", completed: false },
      { title: "Bitcoin Explained", url: "https://youtu.be/s4g1XFU8Gto?si=2nBB7VjnsdbhXQX9", completed: false },
      { title: "Smart Contracts", url: "https://youtu.be/ZE2HxTmxfrI?si=VI5HGWM-wV1W-O7E", completed: false },
    ],
  },
  {
    id: 9,
    title: "Digital Marketing Mastery",
    instructor: "Grace Blue",
    totalLessons: 3,
    image: "",
    nextLesson: "Marketing Fundamentals",
    isPremium: false,
    playlist: [
      { title: "Digital Marketing Intro", url: "https://youtu.be/bixR-KIJKYM?si=VkBWX3uevsfxENG3", completed: false },
      { title: "SEO Basics", url: "https://youtu.be/MYE6T_gd7H0?si=HVbTyuxtf5RfEt9p", completed: false },
      { title: "Social Media Marketing", url: "https://youtu.be/I2pwcAVonKI?si=UUje17f91Y-1XAf9", completed: false },
    ],
  },
  {
    id: 10,
    title: "DevOps & CI/CD",
    instructor: "Hank Silver",
    totalLessons: 3,
    image: "",
    nextLesson: "CI/CD Pipelines",
    isPremium: true,
    price: 29.99,
    playlist: [
      { title: "DevOps Intro", url: "https://youtu.be/Xrgk023l4lI?si=J04jgU4MkmO_fKO_", completed: false },
      { title: "CI/CD Basics", url: "https://youtu.be/scEDHsr3APg?si=jgad0SU7_pxuqOz8", completed: false },
      { title: "Pipeline Automation", url: "https://youtu.be/-hXbGD0R24k?si=mNhICBkQ3UzP7bY4", completed: false },
    ],
  },
  {
    id: 11,
    title: "Game Development with Unity",
    instructor: "Ivy Gold",
    totalLessons: 3,
    image: "",
    nextLesson: "Unity Basics",
    isPremium: true,
    price: 34.99,
    playlist: [
      { title: "Unity Intro", url: "https://youtu.be/iqlH4okiQqg?si=0wSrSU_pwCKNuS7K", completed: false },
      { title: "Unity Scripting Basics", url: "https://youtu.be/Z0Z7xc18CcA?si=ML_9mExSils_I2pe", completed: false },
      { title: "Creating Scenes", url: "https://youtu.be/b9ze5ET3_oY?si=8Vr1rUzGnbm_h1J5", completed: false },
    ],
  },
  {
    id: 12,
    title: "Big Data Analytics",
    instructor: "Jack Purple",
    totalLessons: 3,
    image: "",
    nextLesson: "Data Processing",
    isPremium: false,
    playlist: [
      { title: "Big Data Intro", url: "https://youtu.be/bAyrObl7TYE?si=Kr7HfVEAO6ec_euA", completed: false },
      { title: "Hadoop Basics", url: "https://youtu.be/aReuLtY0YMI?si=AOwdgQtCanI7O-kM", completed: false },
      { title: "Spark Overview", url: "https://youtu.be/IELMSD2kdmk?si=FrUSpf4wL4q40OFP", completed: false },
    ],
  },
  {
    id: 13,
    title: "Internet of Things (IoT)",
    instructor: "Karen Orange",
    totalLessons: 3,
    image: "",
    nextLesson: "IoT Overview",
    isPremium: false,
    playlist: [
      { title: "IoT Intro", url: "https://youtu.be/6mBO2vqLv38?si=mlMSW87CQr7jfac4", completed: false },
      { title: "IoT Sensors & Actuators", url: "https://youtu.be/8VOuA2LFRYA?si=24nDv1a8Z2P9iTZv", completed: false },
      { title: "IoT Projects", url: "https://youtu.be/N_z4OaSuoAA?si=jvWBz7DbT45OiXqY", completed: false },
    ],
  },
  {
    id: 14,
    title: "Ethical Hacking & Pen Testing",
    instructor: "Leo Cyan",
    totalLessons: 3,
    image: "",
    nextLesson: "Intro to Hacking",
    isPremium: true,
    price: 39.99,
    playlist: [
      { title: "Ethical Hacking Intro", url: "https://youtu.be/YXO6he3vbMI?si=FUqAD0wTxK03BK0v", completed: false },
      { title: "Penetration Testing Basics", url: "https://youtu.be/q2t91jLmh3k?si=ISX12qiRUZH11CGj", completed: false },
      { title: "Hacking Tools Overview", url: "https://youtu.be/4dkCxpEn2Rc?si=B2UlvSWam5BqxKxS", completed: false },
    ],
  },
  {
    id: 15,
    title: "AR/VR Development",
    instructor: "Mona Pink",
    totalLessons: 3,
    image: "",
    nextLesson: "AR Basics",
    isPremium: false,
    playlist: [
      { title: "AR Intro", url: "https://youtu.be/h3rKvsFTfPA?si=8U6tO_ewRJf3eZAa", completed: false },
      { title: "VR Basics", url: "https://youtu.be/SBkONGd7jPU?si=zyEQoLHl41zqlUUK", completed: false },
      { title: "AR/VR Projects", url: "https://youtu.be/8-r07M6CWpY?si=cdaXq6ihIH1p3RDM", completed: false },
    ],
  },
  {
    id: 16,
    title: "SQL & Database Management",
    instructor: "Nina Lime",
    totalLessons: 3,
    image: "",
    nextLesson: "SQL Queries",
    isPremium: true,
    price: 19.99,
    playlist: [
      { title: "SQL Intro", url: "https://youtu.be/27axs9dO7AE?si=3cdQFIQ5wkSo7tfG", completed: false },
      { title: "CRUD Operations", url: "https://youtu.be/0iOlEMkOyVE?si=Mg3xQFi_1r5d19PS", completed: false },
      { title: "Database Design Basics", url: "https://youtu.be/5RpUmDEsn1k?si=7QUe1QIfoLzfVo2HO7AE", completed: false },
    ],
  },
  {
    id: 17,
    title: "Business Analytics with Excel",
    instructor: "Oscar Indigo",
    totalLessons: 3,
    image: "",
    nextLesson: "Excel Basics",
    isPremium: false,
    playlist: [
      { title: "Excel Intro", url: "https://youtu.be/fIuoZg4K5AU?si=NGdNosecuYY2dAiQ", completed: false },
      { title: "Pivot Tables", url: "https://youtu.be/m0wI61ahfLc?si=8KtDfZ8NGicBQVu6", completed: false },
      { title: "Charts & Dashboards", url: "https://youtu.be/9NUjHBNWe9M?si=9VKIk4M6h9B4rh4r", completed: false },
    ],
  },
  {
    id: 18,
    title: "Advanced Python Programming",
    instructor: "Paul Violet",
    totalLessons: 3,
    image: "",
    nextLesson: "Advanced Functions",
    isPremium: true,
    price: 29.99,
    playlist: [
      { title: "Advanced Functions", url: "https://youtu.be/kGcUtckifXc?si=y72hUXMJ6UzqXyky", completed: false },
      { title: "OOP in Python", url: "https://youtu.be/q2SGW2VgwAM?si=Tr6Dl6IIdSPHmNR5", completed: false },
      { title: "File Handling & Modules", url: "https://youtu.be/aequTxAvQq4?si=tc5IzoJ6ybUGowr0", completed: false },
    ],
  },
];
